language: java
deploy:
  provider: releases
  api_key:
    secure: R9G/+04GWKDloCmyrl7ZMLu5Qz7FQ5I0ZEXOAeq+uQ+tcUi21v6EJ3s7SL8wx5IyACvosBRXkLpu8pmffT/cTS1QduAEJZkwB+Nl7HwBXiowuXrM/AmjjINGJqzDvfQN9c3LMHOoYHhuhriQwyfZ8kpA0BNxfMPM2I4fU+lOcx2IrSkROOLFr2x+14fMHZdTkl9Lo/56O4S9peG85EGePaiPGQhDf7KVoaz5xkms7hu9+u0SvR+nyF6wlNn3pTrdYVZpiUiZslsga1ivKCMEgN+vgwJfw02nzztd0/2ItzZz6VPGen767vgAtc9auJ1xaO2crOWplSFrwYhlGbnnNGdj510jYgDgd2tj6aTDfXIXiEyE5qeaudLJF0S5qZJMFvVwu86BZ+sU9g3OX9EjD1JCf+O6F8wlx5WX+LWyNCGZ1tk7xrKRPtwI6EthOUMTejgiaCminHCTQwZKRRVyOH/5lgXIzJto93pqvvvmHt1DPxyxH2XBeFEKNqjHQYH9QG53fo6iSxLu5HuAG1V98iNPjmHNV3+CQ3w4PalUZKZ0VXjMGas2Q0/dBjPyUK6pD+VSg2WHgL/YowmTrbHTOB6yzt2ayIeDdPz85ecTP8eGJNOtSLoGu2ghyYCIkp29SaXDFnS6QTlTlySy+KhnDmFl3Z1IKC18qeIjL7f1Pbg=
  file: "target/jmeter-wssecurity-*.jar"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: tilln/jmeter-wssecurity
    tags: true
